version: "3.9"

services:
  deno-server:
    container_name: deno-server
    image: deno
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    ports:
      - "3000:3000"
